
# Install all GUI programs in the application folder
cask_args appdir: "~/Applications", require_sha: true

# If you add apple store applications (mas), uncomment the next line
# brew "mas"

# Must haves

tap "teamookla/speedtest"

brew "teamookla/speedtest/speedtest"
brew "asimov"
brew "python@3.12"
brew "imagemagick"

cask "warp"
cask "firefox@developer-edition"
cask "proton-drive"
cask "proton-mail"
cask "proton-pass"
cask "protonvpn"
cask "notion"
cask "raycast"
cask "lulu"
cask "obsidian"
cask "cloudflare-warp"
cask "rar"
cask "vlc"


# Development

tap "oven-sh/bun"
tap "supabase/tap"

brew "oven-sh/bun/bun"
brew "supabase/tap/supabase"
brew "ddev/ddev"
brew "gh"
brew "git-flow"

cask "orbstack"
cask "pycharm"
cask "visual-studio-code"


# Optional

cask "plex"
cask "microsoft-teams"
cask "yacreader"
cask "qbittorrent"
cask "cleanmymac"
cask "calibre"
cask "grammarly-desktop"
cask "sidequest"
cask "whimsical"
cask "vivaldi"

